### ISSUE TITLE
Logging level no longer respected (in current master)

### ISSUE THREAD

**Issue by merky** [Blackfynn/blackfynn-python#50]
Setting log level is no longer respected anywhere in library/CLI. This issue only applies to the current master branch, as the latest release (2.4.1) does not behave this way.

**Example (env var)**
When the following shell commands are run, it is expected to print various debug-level logs (including all REST calls) because of the value of `BLACKFYNN_LOG_LEVEL`.
```shell
>>> export BLACKFYNN_LOG_LEVEL=DEBUG
>>> bf status
```

**Example (profile setting)**
In the following, `log_level` is set to `DEBUG` in the default connection profile (within `~/.blackfynn/config.ini`). This value/setting is also not being respected by the logger:

```python
from blackfynn import Blackfynn
bf = Blackfynn() # should print debug-level logs
```

**Comment by mattusifer** [comment]
Resolved: https://github.com/Blackfynn/blackfynn-python/pull/51
