### ISSUE TITLE
Expose all available versions of documentation

### ISSUE THREAD

**Issue by clohr** [Blackfynn/blackfynn-python#56]
**Client version:**

2.4.3

**I'm submitting a ...**(check one with "x")

* [ ] bug report
* [x] feature request

**Current behavior:**

Only the latest documentation is available; however if the user knows the url, they can manually navigate to previous versions of the client. 

**Expected behavior:**

Ideally, we should expose the different versions of documentation for each iteration of the client.

**Steps to reproduce:**

Go to http://docs.blackfynn.io/python/latest/. This is the only version visible.

**Related code:**

https://github.com/Blackfynn/sphinx_rtd_theme

**Comment by rlmv** [comment]
Resolved by f74a5e8f9afe099890ad0790f3a456295d0f5850
