### ISSUE TITLE
Accept file list in upload methods

### ISSUE THREAD

**Issue by merky** [Blackfynn/blackfynn-python#60]
**Client version:**

Version `2.4.4`

**I'm submitting a ...**(check one with "x")

* [ ] bug report
* [x] feature request

**Current behavior:**

File uploads into a dataset/collection using the method `dataset.upload` or `collection.upload` take a list of files as separate arguments (e.g. `dataset.upload('file1.dcm', 'file2.dcm', 'file3.dcm')`), but do not actually accept a list object directly as an argument. Thus, with a list `my_files` you can currently upload using `dataset.upload( *my_files )` where the `*` operator expands the list into arguments, but you cannot currently run the expected syntax of `dataset.upload(myfiles)`. 

**Expected behavior:**

Datasets and collections accept a python list-like object as an argument in the `.upload(...)` method.

**Comment by rlmv** [comment]
Resolved by f96ceaba95d667dd9a03962b52f17a86b731f3a6
