### ISSUE TITLE
Owner not being set on objects

### ISSUE THREAD

**Issue by merky** [Blackfynn/blackfynn-python#63]
**Client version:**
2.4.6

**I'm submitting a ...**(check one with "x")

* [x] bug report
* [ ] feature request

**Current behavior:**
```
>>> print dataset.owner_id
None
```

This applies to Datasets, Collections, and Packages.

**Expected behavior:**

```
>>> print dataset.owner_id
N:user:a76a191b-e79c-4524-93a5-3e928cbc4c2b
>>> print dataset.owner_id == bf.profile.id
True
```

**Steps to reproduce:**

```
>>> bf = Blackfynn()
>>> ds = bf.get_dataset('my dataset')
>>> print ds.owner_id
None
```

**Comment by rlmv** [comment]
Resolved by cafc43b2
